### ISSUE TITLE
neovim and neovim-qt install hash check failed

### ISSUE THREAD

**Issue by yigitemres** [lukesampson/scoop#1446]
> Hash check failed for 'https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_64#0.1.7.zip'.
Expected:
    db175f71ca2e8395f4e9f4ae3d67f21ec7ba8925a9568dcbb81bfd1ba71db94d
Actual:
    138ef4d17ffdf5bc0f955c9f7e14f35b817b121a6a49074ab13823245d72a503

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/76f8493f437525ede4be5af2e87d94ffadf77247

**Comment by yigitemres** [comment]
Problem still exist and it is very weird. When I try to install neovim/neovim-qt :

> Hash check failed for 'https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_64#0.1.7.zip'.
Expected:
    c8b1649bffb9d89a369df864c95fbb50a0be7bbc6760783d3f226a8849e366b2
Actual:
    f145f6b5f17514ab65efd019505038f654beae18057accbe34088fd6bd421e5b

But when I open and look neovim.json file hashes are like these:

> 64bit hash: c8b1649bffb9d89a369df864c95fbb50a0be7bbc6760783d3f226a8849e366b2
   32bit hash: ecb9b4eb38671aac7b0a810acf0be1f92ba385dd4254d656854791bb27642922

I wonder that how can scoop reads hash as `f145f6b5f17514ab65efd019505038f654beae18057accbe34088fd6bd421e5b`?

**Comment by r15ch13** [comment]
These are automated builds from the master branch. Now I know why this is not working.
Every time there is a new commit to neovim, appveyor creates a new artifact (zip file) and boom, wrong hash...

**Comment by r15ch13** [comment]
Should be fixed with https://github.com/lukesampson/scoop-extras/commit/3d5730875cdee6e848240f00a97609ea7b1bb9cf

**Comment by yigitemres** [comment]
Problem solved. Thanks r15ch13  for fast response and thanks for lukesampson and all the contributors for such a  good project!
