### ISSUE TITLE
Can't install python

### ISSUE THREAD

**Issue by rioka** [lukesampson/scoop#504]
When i try to install python, I get this output

`installing python (3.5.0)`
`loading https://www.python.org/ftp/python/3.5.0/python-3.5.0.exe from cache...`
`checking hash...ok`
`creating shim for python`
`can't shim python.exe: file doesn't exist`

I actually get a folder C:\Users\name\AppData\Local\scoop\apps\python\3.5.0, containing file python-3.5.0.exe

I can successfully install other apps, anyway (wget or ruby, for example)
Clearing the cache does not change the result.

Any hints?

**Comment by lukesampson** [comment]
Sorry about that, it should be fixed now.

**Comment by zQueal** [comment]
PS C:\Users\zqueal> scoop install python
    installing python (3.5.0)
    loading https://www.python.org/ftp/python/3.5.0/python-3.5.0-amd64.exe#/py350.exe from cache...
    checking hash...ok
    running pre-install script...
    running installer...done
    creating shim for python

As far as I can tell, this issue is still happening.

**Comment by madbub** [comment]
Yeah, I'm having the same issue over here.
I'm still not really sure how scoop works, so don't really know what to look for so I can fix it.

Can anyone give me a few pointers on this? This way I'd be able to look into it.

**Comment by deevus** [comment]
Make sure scoop is updated `scoop update`

**Comment by byxor** [comment]
Re: my previous comment.

I fixed it from control panel by:
1. Repairing python installation
2. Uninstalling python (via its uninstaller)
3. `scoop install python`

**Comment by lukesampson** [comment]
I've added an experimental python install, `python-exp`, which bypasses the official installer in an attempt to avoid these issues. If you'd like to try it, it's `scoop install python-exp`.

**Comment by henryabra** [comment]
`python-exp` worked as expected for me
